(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const STORE='tawazon.app.v1';
const COLORS=['#6f6aff','#29cf9b','#ff9c57','#ef6f91','#42c7dd','#b27cff','#f3c45b'];
const AR_MONTHS=['يناير','فبراير','مارس','أبريل','مايو','يونيو','يوليوز','غشت','شتنبر','أكتوبر','نونبر','دجنبر'];
const AR_DAYS=['الأحد','الاثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت'];const AR_DOW=['ح','ن','ث','ر','خ','ج','س'];
const uid=()=>Math.random().toString(36).slice(2,9)+Date.now().toString(36);
const pad=n=>String(n).padStart(2,'0');
const dateKey=(d=new Date())=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const monthKey=(d=new Date())=>dateKey(d).slice(0,7);
const parseDay=s=>{const [y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d,12)};
const fmtMoney=n=>`${new Intl.NumberFormat('ar-MA-u-nu-latn',{maximumFractionDigits:2}).format(Number(n)||0)} ${state.settings.currency}`;
const fmtDate=s=>parseDay(s).toLocaleDateString('ar-MA-u-nu-latn',{day:'numeric',month:'short'});
const clamp=(n,a,b)=>Math.min(b,Math.max(a,n));
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const icon=id=>`<svg><use href="#${id}"/></svg>`;
function defaultState(){return{
  settings:{name:'',currency:'د.م',pinEnabled:false,pin:''},
  budgets:{},
  habits:[{id:uid(),name:'التعافي من الإباحية والعادة السرية',startDate:dateKey(),color:'#6f6aff',main:true,records:{}}],
  pushups:{plan:{title:'خطة Push-up',days:[10,0,12,0,15,0,0],weeklyGoal:37},sessions:[]},
  kegel:{level:'beginner',sessions:[]},
  ui:{budgetMonth:monthKey(),calendarMonth:monthKey()}
}}
function load(){try{const v=JSON.parse(localStorage.getItem(STORE));if(v&&v.settings)return v}catch(e){}return defaultState()}
let state=load();
function normalize(){const d=defaultState();state.settings={...d.settings,...state.settings};state.budgets=state.budgets||{};state.habits=Array.isArray(state.habits)?state.habits:d.habits;if(!state.habits.some(h=>h.main))state.habits.unshift(d.habits[0]);state.pushups={...d.pushups,...state.pushups,plan:{...d.pushups.plan,...(state.pushups?.plan||{})},sessions:state.pushups?.sessions||[]};state.kegel={...d.kegel,...state.kegel,sessions:state.kegel?.sessions||[]};state.ui={...d.ui,...state.ui}}
normalize();
function save(){localStorage.setItem(STORE,JSON.stringify(state))}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2200)}
function budget(){const key=state.ui.budgetMonth;return state.budgets[key]||(state.budgets[key]={name:'ميزانية الشهر',income:0,categories:[],expenses:[],goals:[]})}
function diffDays(a,b){return Math.round((parseDay(b)-parseDay(a))/86400000)}
function mainHabit(){return state.habits.find(h=>h.main)}
function mainStreak(){const h=mainHabit();if(!h)return 0;const today=dateKey();if(h.startDate>today)return 0;let n=diffDays(h.startDate,today)+1;for(const [d,v] of Object.entries(h.records||{})){if(v==='missed'&&d>=h.startDate&&d<=today)n=Math.min(n,diffDays(d,today));}return Math.max(0,n)}
function isDone(h,d=dateKey()){return h.records?.[d]==='done'}
function renderAll(){renderHeader();renderHome();renderBudget();renderHabits();renderPushups();renderKegel()}
function renderHeader(){const hr=new Date().getHours();$('#greeting').textContent=hr<12?'صباح الخير':hr<18?'مساء الخير':'أهلاً بك';}
function setPage(name){$$('.page').forEach(p=>p.classList.toggle('active',p.dataset.page===name));$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.pageTarget===name));const titles={home:'نظرة عامة',budget:'ميزانيتي',habits:'العادات',pushups:'تمارين Push-up',kegel:'تمارين كيجل'};$('#pageTitle').textContent=titles[name];scrollTo({top:0,behavior:'smooth'});if(name==='home')renderHome()}
$$('[data-page-target]').forEach(b=>b.onclick=()=>setPage(b.dataset.pageTarget));$$('[data-go]').forEach(b=>b.onclick=()=>setPage(b.dataset.go));

function renderHome(){const now=new Date(), b=state.budgets[monthKey()]||{income:0,expenses:[],goals:[]};const spent=(b.expenses||[]).reduce((s,x)=>s+Number(x.amount),0);const saved=(b.goals||[]).reduce((s,x)=>s+Number(x.saved),0);const habitsDone=state.habits.filter(h=>isDone(h)).length;const todayPush=state.pushups.sessions.filter(x=>x.date===dateKey()).reduce((s,x)=>s+x.reps,0);const todayK=state.kegel.sessions.filter(x=>x.date===dateKey()).length;
$('#heroDate').textContent=`${AR_DAYS[now.getDay()]}، ${now.getDate()} ${AR_MONTHS[now.getMonth()]}`;$('#homeBalance').textContent=fmtMoney(Number(b.income)-spent-saved);$('#homeHabits').textContent=`${habitsDone} / ${state.habits.length}`;$('#homePushups').textContent=`${todayPush} تكرار`;$('#homeKegel').textContent=`${todayK} جلسة`;
const possible=state.habits.length+2;const done=habitsDone+(todayPush>0?1:0)+(todayK>0?1:0);const pct=possible?Math.round(done/possible*100):0;$('#dailyRing').style.setProperty('--p',`${pct*3.6}deg`);$('#dailyRing strong').textContent=`${pct}%`;$('#heroSummary').textContent=pct>=100?'أكملت كل مهام اليوم، أحسنت!':pct>=50?'تقدم جميل، بقي القليل.':'ابدأ بخطوة صغيرة اليوم.';
const tasks=[...state.habits.map(h=>({title:h.name,sub:isDone(h)?'مكتملة اليوم':'اضغط لتسجيلها',done:isDone(h),go:'habits'})),{title:'تمرين Push-up',sub:todayPush?`${todayPush} تكرار اليوم`:'لم تسجل تمريناً اليوم',done:todayPush>0,go:'pushups'},{title:'جلسة كيجل',sub:todayK?`${todayK} جلسة اليوم`:'جلسة قصيرة ومنظمة',done:todayK>0,go:'kegel'}];$('#todayTasks').innerHTML=tasks.map(t=>`<button class="list-item glass" data-task-go="${t.go}"><span class="item-icon" style="--tone:${t.done?'#42dba9':'#8d87ff'}">${icon(t.done?'i-check':'i-target')}</span><span class="item-main"><strong>${esc(t.title)}</strong><small>${esc(t.sub)}</small></span>${icon('i-chevron')}</button>`).join('');$$('[data-task-go]').forEach(x=>x.onclick=()=>setPage(x.dataset.taskGo));
const weekStart=new Date();weekStart.setDate(weekStart.getDate()-6);const wPush=state.pushups.sessions.filter(x=>parseDay(x.date)>=parseDay(dateKey(weekStart))).reduce((s,x)=>s+x.reps,0);const wK=state.kegel.sessions.filter(x=>parseDay(x.date)>=parseDay(dateKey(weekStart))).length;$('#weeklyInsight').textContent=`خلال آخر 7 أيام: ${wPush} تمرين Push-up و${wK} جلسات كيجل. سلسلة التعافي الحالية ${mainStreak()} يوم.`}

function renderBudget(){const b=budget();const spent=b.expenses.reduce((s,x)=>s+Number(x.amount),0),saved=b.goals.reduce((s,x)=>s+Number(x.saved),0),balance=Number(b.income)-spent-saved;const [y,m]=state.ui.budgetMonth.split('-').map(Number);$('#budgetMonth').textContent=`${AR_MONTHS[m-1]} ${y}`;$('#budgetIncome').textContent=fmtMoney(b.income);$('#budgetSpent').textContent=fmtMoney(spent);$('#budgetSaved').textContent=fmtMoney(saved);$('#budgetBalance').textContent=fmtMoney(balance);$('#budgetProgress').style.width=`${clamp((spent+saved)/(Number(b.income)||1)*100,0,100)}%`;
$('#categoryList').innerHTML=b.categories.length?b.categories.map((c,i)=>{const used=b.expenses.filter(e=>e.categoryId===c.id).reduce((s,e)=>s+Number(e.amount),0),p=clamp(used/(Number(c.limit)||1)*100,0,100);return`<article class="category-card" style="--color:${c.color}"><h3>${esc(c.name)}</h3><div class="amount-line"><b>${fmtMoney(used)}</b><span>من ${fmtMoney(c.limit)}</span></div><div class="progress"><i style="width:${p}%;background:${c.color}"></i></div><div class="card-actions"><button class="mini-action" data-edit-cat="${i}">${icon('i-edit')}</button><button class="mini-action" data-del-cat="${i}">${icon('i-trash')}</button></div></article>`}).join(''):empty('i-wallet','أضف أول فئة وقسّم أجرتك كما يناسبك.');
$('#expenseList').innerHTML=b.expenses.length?[...b.expenses].sort((a,z)=>z.date.localeCompare(a.date)).slice(0,20).map((e,i)=>{const real=b.expenses.indexOf(e),cat=b.categories.find(c=>c.id===e.categoryId);return listRow(cat?.name?.slice(0,1)||'م',e.note||cat?.name||'مصروف',`${fmtMoney(e.amount)} · ${fmtDate(e.date)}`,real,'exp')}).join(''):empty('i-coins','لا توجد مصاريف مسجلة في هذا الشهر.');
$('#goalList').innerHTML=b.goals.length?b.goals.map((g,i)=>{const p=clamp(Number(g.saved)/(Number(g.target)||1)*100,0,100);return`<article class="list-item"><span class="item-icon">${icon('i-target')}</span><span class="item-main"><strong>${esc(g.name)}</strong><small>${fmtMoney(g.saved)} من ${fmtMoney(g.target)} · ${Math.round(p)}%</small><span class="progress"><i style="width:${p}%"></i></span></span><span class="item-actions"><button class="mini-action" data-edit-goal="${i}">${icon('i-edit')}</button><button class="mini-action" data-del-goal="${i}">${icon('i-trash')}</button></span></article>`}).join(''):empty('i-target','أضف هدف ادخار وتابع تقدمك نحوه.');
$$('[data-edit-cat]').forEach(x=>x.onclick=()=>categoryModal(Number(x.dataset.editCat)));$$('[data-del-cat]').forEach(x=>x.onclick=()=>removeItem('categories',Number(x.dataset.delCat),'الفئة'));$$('[data-edit-exp]').forEach(x=>x.onclick=()=>expenseModal(Number(x.dataset.editExp)));$$('[data-del-exp]').forEach(x=>x.onclick=()=>removeItem('expenses',Number(x.dataset.delExp),'المصروف'));$$('[data-edit-goal]').forEach(x=>x.onclick=()=>goalModal(Number(x.dataset.editGoal)));$$('[data-del-goal]').forEach(x=>x.onclick=()=>removeItem('goals',Number(x.dataset.delGoal),'الهدف'))}
function empty(ic,text){return`<div class="empty-state">${icon(ic)}<div>${text}</div></div>`}
function listRow(letter,title,sub,i,type){return`<article class="list-item"><span class="item-icon">${esc(letter)}</span><span class="item-main"><strong>${esc(title)}</strong><small>${esc(sub)}</small></span><span class="item-actions"><button class="mini-action" data-edit-${type}="${i}">${icon('i-edit')}</button><button class="mini-action" data-del-${type}="${i}">${icon('i-trash')}</button></span></article>`}
function removeItem(key,i,label){if(confirm(`حذف ${label}؟`)){budget()[key].splice(i,1);save();renderAll();toast('تم الحذف')}}
$('#prevMonth').onclick=()=>shiftMonth(-1);$('#nextMonth').onclick=()=>shiftMonth(1);function shiftMonth(n){const [y,m]=state.ui.budgetMonth.split('-').map(Number),d=new Date(y,m-1+n,1);state.ui.budgetMonth=monthKey(d);save();renderBudget()}$('#monthPickerBtn').onclick=()=>{const i=$('#monthInput');i.value=state.ui.budgetMonth;i.showPicker?i.showPicker():i.click()};$('#monthInput').onchange=e=>{if(e.target.value){state.ui.budgetMonth=e.target.value;save();renderBudget()}}

function field(name,label,type='text',value='',extra=''){return`<div class="field"><label for="f_${name}">${label}</label><input id="f_${name}" name="${name}" type="${type}" value="${esc(value)}" ${extra}></div>`}
let modalSubmit=null;function openModal(title,body,onSubmit){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=body;modalSubmit=onSubmit;$('#modal').classList.remove('hidden');setTimeout(()=>$('#modal input')?.focus(),120)}function closeModal(){$('#modal').classList.add('hidden');modalSubmit=null}$('#modalClose').onclick=closeModal;$('#modal').onclick=e=>{if(e.target===$('#modal'))closeModal()};$('#modalForm').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));if(modalSubmit?.(data)!==false){closeModal();save();renderAll()}}
$('#editIncomeBtn').onclick=()=>{const b=budget();openModal('الدخل واسم الميزانية',field('name','اسم الميزانية','text',b.name,'required maxlength="40"')+field('income','الدخل الشهري','number',b.income,'required min="0" step="0.01"'),d=>{b.name=d.name.trim();b.income=Number(d.income);toast('تم تحديث الميزانية')})};
$('#addCategoryBtn').onclick=()=>categoryModal();function categoryModal(i){const b=budget(),c=i==null?{name:'',limit:'',color:COLORS[b.categories.length%COLORS.length]}:b.categories[i];openModal(i==null?'فئة جديدة':'تعديل الفئة',field('name','اسم الفئة','text',c.name,'required maxlength="30"')+field('limit','المبلغ المخصص','number',c.limit,'required min="0" step="0.01"')+`<div class="field"><label>اللون</label><input name="color" type="color" value="${c.color}"></div>`,d=>{const v={id:c.id||uid(),name:d.name.trim(),limit:Number(d.limit),color:d.color};i==null?b.categories.push(v):b.categories[i]=v;toast('تم حفظ الفئة')})}
$('#addExpenseBtn').onclick=()=>expenseModal();function expenseModal(i){const b=budget();if(!b.categories.length){toast('أضف فئة أولاً');return}const e=i==null?{amount:'',categoryId:b.categories[0].id,date:dateKey(),note:''}:b.expenses[i];openModal(i==null?'مصروف جديد':'تعديل المصروف',`<div class="field"><label>الفئة</label><select name="categoryId">${b.categories.map(c=>`<option value="${c.id}" ${c.id===e.categoryId?'selected':''}>${esc(c.name)}</option>`).join('')}</select></div>`+field('amount','المبلغ','number',e.amount,'required min="0.01" step="0.01"')+field('date','التاريخ','date',e.date,'required')+field('note','ملاحظة','text',e.note,'maxlength="60"'),d=>{const v={id:e.id||uid(),categoryId:d.categoryId,amount:Number(d.amount),date:d.date,note:d.note.trim()};i==null?b.expenses.push(v):b.expenses[i]=v;toast('تم حفظ المصروف')})}
$('#addGoalBtn').onclick=()=>goalModal();function goalModal(i){const b=budget(),g=i==null?{name:'',target:'',saved:0}:b.goals[i];openModal(i==null?'هدف ادخار جديد':'تعديل هدف الادخار',field('name','اسم الهدف','text',g.name,'required maxlength="40"')+field('target','المبلغ المستهدف','number',g.target,'required min="1" step="0.01"')+field('saved','المبلغ المدخر','number',g.saved,'required min="0" step="0.01"'),d=>{const v={id:g.id||uid(),name:d.name.trim(),target:Number(d.target),saved:Number(d.saved)};i==null?b.goals.push(v):b.goals[i]=v;toast('تم حفظ الهدف')})}

function renderHabits(){const h=mainHabit(),streak=mainStreak();$('#mainHabitCard').innerHTML=`<span class="eyebrow">العادة الرئيسية</span><h2>${esc(h.name)}</h2><div class="streak">${streak}</div><div class="streak-label">${streak===1?'يوم ناجح':'أيام متتالية'}</div><div class="recovery-actions"><button id="mainDone" class="primary-button">${icon('i-check')} ${isDone(h)?'مسجل اليوم':'سجل يوم ناجح'}</button><button id="mainSlip" class="secondary-button">${icon('i-x')} تسجيل تعثر</button></div><button id="editMainHabit" class="text-button" style="margin:10px auto 0">${icon('i-edit')} تعديل البداية والاسم</button>`;
$('#habitList').innerHTML=state.habits.map((x,i)=>`<article class="habit-row"><button class="habit-check ${isDone(x)?'done':''}" data-toggle-habit="${i}">${icon('i-check')}</button><span class="item-main"><strong>${esc(x.name)}</strong><small>${x.main?'العادة الرئيسية':`${Object.values(x.records||{}).filter(v=>v==='done').length} مرة ناجحة`}</small></span>${!x.main?`<span class="item-actions"><button class="mini-action" data-edit-habit="${i}">${icon('i-edit')}</button><button class="mini-action" data-del-habit="${i}">${icon('i-trash')}</button></span>`:''}</article>`).join('');
$('#mainDone').onclick=()=>{h.records[dateKey()]='done';if(h.startDate>dateKey())h.startDate=dateKey();save();renderAll();toast('تم تسجيل اليوم بنجاح')};$('#mainSlip').onclick=()=>{if(confirm('تسجيل تعثر اليوم وبدء سلسلة جديدة غداً؟')){h.records[dateKey()]='missed';const t=new Date();t.setDate(t.getDate()+1);h.startDate=dateKey(t);save();renderAll();toast('تم التسجيل. ابدأ من جديد بهدوء')}};$('#editMainHabit').onclick=()=>habitModal(state.habits.indexOf(h),true);$$('[data-toggle-habit]').forEach(x=>x.onclick=()=>{const z=state.habits[Number(x.dataset.toggleHabit)],d=dateKey();z.records[d]=isDone(z)?null:'done';if(z.records[d]===null)delete z.records[d];save();renderAll()});$$('[data-edit-habit]').forEach(x=>x.onclick=()=>habitModal(Number(x.dataset.editHabit)));$$('[data-del-habit]').forEach(x=>x.onclick=()=>{const i=Number(x.dataset.delHabit);if(confirm('حذف هذه العادة وسجلها؟')){state.habits.splice(i,1);save();renderAll()}});renderCalendar()}
$('#addHabitBtn').onclick=()=>habitModal();function habitModal(i,main=false){const h=i==null?{name:'',startDate:dateKey(),color:COLORS[state.habits.length%COLORS.length]}:state.habits[i];openModal(i==null?'عادة جديدة':'تعديل العادة',field('name','اسم العادة','text',h.name,'required maxlength="55"')+(main?field('startDate','تاريخ بداية السلسلة','date',h.startDate,'required'):''),d=>{if(i==null)state.habits.push({id:uid(),name:d.name.trim(),startDate:dateKey(),color:h.color,main:false,records:{}});else{h.name=d.name.trim();if(main)h.startDate=d.startDate}toast('تم حفظ العادة')})}
function renderCalendar(){const [y,m]=state.ui.calendarMonth.split('-').map(Number),first=new Date(y,m-1,1),start=new Date(y,m-1,1-first.getDay());$('#calTitle').textContent=`${AR_MONTHS[m-1]} ${y}`;const h=mainHabit();let html='';for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const k=dateKey(d),v=h.records?.[k],classes=['calendar-day'];if(d.getMonth()!==m-1)classes.push('other');if(k===dateKey())classes.push('today');if(v==='done'||(!v&&k>=h.startDate&&k<=dateKey()&&v!=='missed'))classes.push('done');if(v==='missed')classes.push('missed');html+=`<span class="${classes.join(' ')}">${d.getDate()}</span>`}$('#habitCalendar').innerHTML=html}
$('#calPrev').onclick=()=>calShift(-1);$('#calNext').onclick=()=>calShift(1);function calShift(n){const [y,m]=state.ui.calendarMonth.split('-').map(Number),d=new Date(y,m-1+n,1);state.ui.calendarMonth=monthKey(d);save();renderCalendar()}

let pushCount=0;function renderPushups(){const p=state.pushups.plan,today=new Date().getDay(),todayGoal=Number(p.days[today]||0);$('#pushupPlanTitle').textContent=p.title;$('#pushupPlanMeta').textContent=todayGoal?`هدف اليوم ${todayGoal} تكرار`:'اليوم مخصص للراحة';$('#pushCounter').textContent=pushCount;$('#pushPlan').innerHTML=`<strong>الهدف الأسبوعي: ${p.weeklyGoal} تكرار</strong><div class="plan-days">${p.days.map((v,i)=>`<span class="plan-day ${i===today?'active':''}">${AR_DOW[i]}<b>${v||'—'}</b></span>`).join('')}</div>`;$('#pushHistory').innerHTML=state.pushups.sessions.length?[...state.pushups.sessions].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,14).map((s,i)=>listRow('P',`${s.reps} تكرار`,fmtDate(s.date),state.pushups.sessions.indexOf(s),'push')).join(''):empty('i-dumbbell','سجل أول تمرين ليظهر هنا.');$$('[data-edit-push]').forEach(x=>x.onclick=()=>editPushSession(Number(x.dataset.editPush)));$$('[data-del-push]').forEach(x=>x.onclick=()=>{const i=Number(x.dataset.delPush);if(confirm('حذف هذا التمرين؟')){state.pushups.sessions.splice(i,1);save();renderAll()}})}
$('#pushMinus').onclick=()=>{pushCount=Math.max(0,pushCount-1);renderPushups()};$('#pushPlus').onclick=()=>{pushCount++;renderPushups()};$$('[data-add]').forEach(b=>b.onclick=()=>{pushCount+=Number(b.dataset.add);renderPushups()});$('#savePushSession').onclick=()=>{if(!pushCount)return toast('أدخل عدد التكرارات أولاً');state.pushups.sessions.push({id:uid(),date:dateKey(),reps:pushCount});pushCount=0;save();renderAll();toast('تم حفظ التمرين')};
$('#editPushPlan').onclick=()=>{const p=state.pushups.plan;openModal('تعديل خطة Push-up',field('title','اسم الخطة','text',p.title,'required maxlength="40"')+`<p class="form-note">ضع 0 في أيام الراحة.</p><div class="field-row">${p.days.map((v,i)=>field(`d${i}`,AR_DAYS[i],'number',v,'min="0" max="999"')).join('')}</div>`,d=>{p.title=d.title.trim();p.days=p.days.map((_,i)=>Number(d[`d${i}`])||0);p.weeklyGoal=p.days.reduce((a,b)=>a+b,0);toast('تم تحديث الخطة')})};function editPushSession(i){const s=state.pushups.sessions[i];openModal('تعديل التمرين',field('reps','عدد التكرارات','number',s.reps,'required min="1" max="9999"')+field('date','التاريخ','date',s.date,'required'),d=>{s.reps=Number(d.reps);s.date=d.date;toast('تم تعديل التمرين')})}

const LEVELS={beginner:{name:'مبتدئ',hold:5,rest:5,rounds:10,desc:'5 ثوان شد · 5 راحة · 10 جولات'},intermediate:{name:'متوسط',hold:8,rest:8,rounds:10,desc:'8 ثوان شد · 8 راحة · 10 جولات'},advanced:{name:'متقدم',hold:10,rest:10,rounds:12,desc:'10 ثوان شد · 10 راحة · 12 جولة'}};let kt={running:false,phase:'hold',round:0,left:0,total:0,interval:null};
function renderKegel(){const l=LEVELS[state.kegel.level];$('#kegelLevels').innerHTML=Object.entries(LEVELS).map(([k,v])=>`<article class="level-card ${k===state.kegel.level?'selected':''}"><span class="level-dot">${v.hold}</span><div><strong>${v.name}</strong><small>${v.desc}</small></div><button data-level="${k}">${k===state.kegel.level?'محدد':'اختيار'}</button></article>`).join('');$$('[data-level]').forEach(x=>x.onclick=()=>{if(kt.running)return toast('أوقف الجلسة قبل تغيير المستوى');state.kegel.level=x.dataset.level;save();renderKegel()});$('#kegelHistory').innerHTML=state.kegel.sessions.length?[...state.kegel.sessions].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,14).map((s,i)=>listRow('K',`${LEVELS[s.level]?.name||'جلسة'} · ${s.rounds} جولات`,fmtDate(s.date),state.kegel.sessions.indexOf(s),'kegel')).join(''):empty('i-pulse','أكمل أول جلسة لتظهر في السجل.');$$('[data-edit-kegel]').forEach(x=>x.onclick=()=>editKegel(Number(x.dataset.editKegel)));$$('[data-del-kegel]').forEach(x=>x.onclick=()=>{const i=Number(x.dataset.delKegel);if(confirm('حذف الجلسة؟')){state.kegel.sessions.splice(i,1);save();renderAll()}});updateKegelUI()}
function updateKegelUI(){const l=LEVELS[state.kegel.level],duration=kt.phase==='hold'?l.hold:l.rest,p=kt.running?(duration-kt.left)/duration*360:0;$('#kegelTimer').style.setProperty('--timer',`${p}deg`);$('#kegelTimer strong').textContent=kt.running?`00:${pad(kt.left)}`:'00:00';$('#kegelRound').textContent=kt.running?`${kt.round+1} / ${l.rounds}`:`0 / ${l.rounds}`;$('#kegelPhase').textContent=kt.running?(kt.phase==='hold'?'شد بلطف':'استرخِ'):'جاهز للبدء';$('#kegelCue').textContent=kt.running?(kt.phase==='hold'?'شد عضلات قاع الحوض بلطف مع التنفس الطبيعي.':'أرخِ العضلات تماماً وخذ نفساً هادئاً.'):'تنفّس بشكل طبيعي ولا تشد البطن أو الأرداف.';$('#kegelStart').innerHTML=kt.running?`${icon('i-pause')} إيقاف مؤقت`:`${icon('i-play')} ابدأ`}
$('#kegelStart').onclick=()=>{if(kt.running){clearInterval(kt.interval);kt.running=false;updateKegelUI();return}const l=LEVELS[state.kegel.level];if(!kt.left){kt.phase='hold';kt.round=0;kt.left=l.hold;kt.total=0}kt.running=true;updateKegelUI();kt.interval=setInterval(kegelTick,1000)};function kegelTick(){const l=LEVELS[state.kegel.level];kt.left--;kt.total++;if(kt.left<=0){if(kt.phase==='hold'){kt.phase='rest';kt.left=l.rest}else{kt.round++;if(kt.round>=l.rounds){finishKegel();return}else{kt.phase='hold';kt.left=l.hold}}}updateKegelUI()}
function finishKegel(){clearInterval(kt.interval);state.kegel.sessions.push({id:uid(),date:dateKey(),level:state.kegel.level,rounds:LEVELS[state.kegel.level].rounds,duration:kt.total});kt={running:false,phase:'hold',round:0,left:0,total:0,interval:null};save();renderAll();toast('أحسنت، اكتملت الجلسة')}
$('#kegelStop').onclick=()=>{clearInterval(kt.interval);kt={running:false,phase:'hold',round:0,left:0,total:0,interval:null};updateKegelUI()};function editKegel(i){const s=state.kegel.sessions[i];openModal('تعديل الجلسة',field('date','التاريخ','date',s.date,'required')+field('rounds','عدد الجولات','number',s.rounds,'required min="1" max="100"'),d=>{s.date=d.date;s.rounds=Number(d.rounds);toast('تم تعديل الجلسة')})}

$('#settingsBtn').onclick=()=>settingsModal();function settingsModal(){const s=state.settings;openModal('الإعدادات',field('name','اسمك (اختياري)','text',s.name,'maxlength="30"')+field('currency','رمز العملة','text',s.currency,'required maxlength="8"')+`<div class="switch-row"><span><strong>قفل PIN</strong><small style="display:block;color:#98a5b9">يُحفظ على هذا الجهاز فقط</small></span><button type="button" id="pinSwitch" class="switch ${s.pinEnabled?'on':''}"><i></i></button></div><div id="pinField" class="${s.pinEnabled?'':'hidden'}">${field('pin','رمز من 4 أرقام','password',s.pin,'inputmode="numeric" pattern="[0-9]{4}" maxlength="4"')}</div><p class="form-note">بياناتك تبقى داخل متصفحك ولا تُرسل إلى أي خادم.</p><button type="button" id="lockNow" class="secondary-button full">${icon('i-lock')} قفل التطبيق الآن</button><button type="button" id="resetApp" class="danger-button">حذف جميع بيانات التطبيق</button>`,d=>{const enabled=$('#pinSwitch').classList.contains('on');if(enabled&&!/^\d{4}$/.test(d.pin)){toast('أدخل PIN من 4 أرقام');return false}s.name=d.name.trim();s.currency=d.currency.trim();s.pinEnabled=enabled;s.pin=enabled?d.pin:'';toast('تم حفظ الإعدادات')});setTimeout(()=>{$('#pinSwitch').onclick=()=>{$('#pinSwitch').classList.toggle('on');$('#pinField').classList.toggle('hidden')};$('#lockNow').onclick=()=>{if(!state.settings.pinEnabled)return toast('فعّل قفل PIN أولاً');closeModal();showLock()};$('#resetApp').onclick=()=>{if(confirm('سيتم حذف كل بيانات الميزانية والعادات والتمارين. هل أنت متأكد؟')){localStorage.removeItem(STORE);state=defaultState();pushCount=0;save();closeModal();renderAll();toast('تمت إعادة ضبط التطبيق')}}},0)}

let pinEntry='',lockFails=0,blockedUntil=0;function buildPad(){const padEl=$('#pinPad');padEl.innerHTML=[1,2,3,4,5,6,7,8,9,'⌫',0].map(n=>`<button data-key="${n}">${n}</button>`).join('');$$('[data-key]',padEl).forEach(b=>b.onclick=()=>pinKey(b.dataset.key))}function pinKey(k){if(Date.now()<blockedUntil)return lockMessage();if(k==='⌫')pinEntry=pinEntry.slice(0,-1);else if(pinEntry.length<4)pinEntry+=k;$$('#pinDots b').forEach((d,i)=>d.classList.toggle('on',i<pinEntry.length));if(pinEntry.length===4)setTimeout(checkPin,100)}function checkPin(){if(pinEntry===state.settings.pin){$('#lockScreen').classList.add('hidden');pinEntry='';lockFails=0}else{pinEntry='';lockFails++;$$('#pinDots b').forEach(d=>d.classList.remove('on'));if(lockFails>=5){blockedUntil=Date.now()+30000;lockFails=0;lockMessage();const t=setInterval(()=>{lockMessage();if(Date.now()>=blockedUntil)clearInterval(t)},1000)}else $('#lockMessage').textContent=`رمز غير صحيح · بقيت ${5-lockFails} محاولات`}}function lockMessage(){const sec=Math.max(0,Math.ceil((blockedUntil-Date.now())/1000));$('#lockMessage').textContent=sec?`انتظر ${sec} ثانية قبل المحاولة`:'يمكنك المحاولة الآن'}function showLock(){$('#lockScreen').classList.remove('hidden');pinEntry='';$$('#pinDots b').forEach(d=>d.classList.remove('on'));$('#lockMessage').textContent=''}

document.addEventListener('contextmenu',e=>e.preventDefault());document.addEventListener('gesturestart',e=>e.preventDefault());buildPad();renderAll();if(state.settings.pinEnabled&&state.settings.pin)showLock();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
})();
